### ISSUE TITLE
MeCab build error

### ISSUE THREAD

**Issue by ShinkaNao** [chezou/MeCab.jl#15]
I just installed Mecab package on the WINDOWS 10 PC using the following command：
         Pkg.add("MeCab")
But when I build the MeCab package, the following error occurred：
         LoadError: None of the selected providers can install dependency libmecab.

How to install the dependency libmecab?
PS：My computer is mecab installed.

Thanks.

**Comment by ShinkaNao** [comment]
I tested this package under Ubuntu14. It has worked.
Is this package can only be supported by unix-like environment? @chezou 
Help !

**Comment by chezou** [comment]
@ShinkaNao I'm sorry to say this but building MeCab on Windows automatically is really hard and I don't plan to add this feature now. Of course, this is OSS, so your contribution is welcome :)
